name: Feature Request
description: Make a feature request or suggestion. For large proposed changes and RFCs, please create a discussion instead.
labels: [enhancement]
body:
- type: markdown
  attributes:
    value: |
      ## Feature Request
- type: textarea
  attributes:
    label: Describe the feature and provide any additional context
